//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceTLAExterno.FarmAgro {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FarmAgro.WebService_FarmAgroSoap")]
    public interface WebService_FarmAgroSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrdenesExpedicion_03", ReplyAction="*")]
        WebServiceTLAExterno.FarmAgro.OrdenesExpedicion_03Response OrdenesExpedicion_03(WebServiceTLAExterno.FarmAgro.OrdenesExpedicion_03Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrdenesExpedicion_03", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceTLAExterno.FarmAgro.OrdenesExpedicion_03Response> OrdenesExpedicion_03Async(WebServiceTLAExterno.FarmAgro.OrdenesExpedicion_03Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrdenesASN_01", ReplyAction="*")]
        WebServiceTLAExterno.FarmAgro.OrdenesASN_01Response OrdenesASN_01(WebServiceTLAExterno.FarmAgro.OrdenesASN_01Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrdenesASN_01", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceTLAExterno.FarmAgro.OrdenesASN_01Response> OrdenesASN_01Async(WebServiceTLAExterno.FarmAgro.OrdenesASN_01Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Materiales_11", ReplyAction="*")]
        WebServiceTLAExterno.FarmAgro.Materiales_11Response Materiales_11(WebServiceTLAExterno.FarmAgro.Materiales_11Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Materiales_11", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceTLAExterno.FarmAgro.Materiales_11Response> Materiales_11Async(WebServiceTLAExterno.FarmAgro.Materiales_11Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrdenesExpedicion_03Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrdenesExpedicion_03", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceTLAExterno.FarmAgro.OrdenesExpedicion_03RequestBody Body;
        
        public OrdenesExpedicion_03Request() {
        }
        
        public OrdenesExpedicion_03Request(WebServiceTLAExterno.FarmAgro.OrdenesExpedicion_03RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrdenesExpedicion_03RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Json;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string data;
        
        public OrdenesExpedicion_03RequestBody() {
        }
        
        public OrdenesExpedicion_03RequestBody(string Json, string data) {
            this.Json = Json;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrdenesExpedicion_03Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrdenesExpedicion_03Response", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceTLAExterno.FarmAgro.OrdenesExpedicion_03ResponseBody Body;
        
        public OrdenesExpedicion_03Response() {
        }
        
        public OrdenesExpedicion_03Response(WebServiceTLAExterno.FarmAgro.OrdenesExpedicion_03ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrdenesExpedicion_03ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool OrdenesExpedicion_03Result;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string data;
        
        public OrdenesExpedicion_03ResponseBody() {
        }
        
        public OrdenesExpedicion_03ResponseBody(bool OrdenesExpedicion_03Result, string data) {
            this.OrdenesExpedicion_03Result = OrdenesExpedicion_03Result;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrdenesASN_01Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrdenesASN_01", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceTLAExterno.FarmAgro.OrdenesASN_01RequestBody Body;
        
        public OrdenesASN_01Request() {
        }
        
        public OrdenesASN_01Request(WebServiceTLAExterno.FarmAgro.OrdenesASN_01RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrdenesASN_01RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Json;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string data;
        
        public OrdenesASN_01RequestBody() {
        }
        
        public OrdenesASN_01RequestBody(string Json, string data) {
            this.Json = Json;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrdenesASN_01Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrdenesASN_01Response", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceTLAExterno.FarmAgro.OrdenesASN_01ResponseBody Body;
        
        public OrdenesASN_01Response() {
        }
        
        public OrdenesASN_01Response(WebServiceTLAExterno.FarmAgro.OrdenesASN_01ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrdenesASN_01ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool OrdenesASN_01Result;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string data;
        
        public OrdenesASN_01ResponseBody() {
        }
        
        public OrdenesASN_01ResponseBody(bool OrdenesASN_01Result, string data) {
            this.OrdenesASN_01Result = OrdenesASN_01Result;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Materiales_11Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Materiales_11", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceTLAExterno.FarmAgro.Materiales_11RequestBody Body;
        
        public Materiales_11Request() {
        }
        
        public Materiales_11Request(WebServiceTLAExterno.FarmAgro.Materiales_11RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Materiales_11RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string json;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string data;
        
        public Materiales_11RequestBody() {
        }
        
        public Materiales_11RequestBody(string json, string data) {
            this.json = json;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Materiales_11Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Materiales_11Response", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceTLAExterno.FarmAgro.Materiales_11ResponseBody Body;
        
        public Materiales_11Response() {
        }
        
        public Materiales_11Response(WebServiceTLAExterno.FarmAgro.Materiales_11ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Materiales_11ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Materiales_11Result;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string data;
        
        public Materiales_11ResponseBody() {
        }
        
        public Materiales_11ResponseBody(bool Materiales_11Result, string data) {
            this.Materiales_11Result = Materiales_11Result;
            this.data = data;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_FarmAgroSoapChannel : WebServiceTLAExterno.FarmAgro.WebService_FarmAgroSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_FarmAgroSoapClient : System.ServiceModel.ClientBase<WebServiceTLAExterno.FarmAgro.WebService_FarmAgroSoap>, WebServiceTLAExterno.FarmAgro.WebService_FarmAgroSoap {
        
        public WebService_FarmAgroSoapClient() {
        }
        
        public WebService_FarmAgroSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_FarmAgroSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_FarmAgroSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_FarmAgroSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceTLAExterno.FarmAgro.OrdenesExpedicion_03Response WebServiceTLAExterno.FarmAgro.WebService_FarmAgroSoap.OrdenesExpedicion_03(WebServiceTLAExterno.FarmAgro.OrdenesExpedicion_03Request request) {
            return base.Channel.OrdenesExpedicion_03(request);
        }
        
        public bool OrdenesExpedicion_03(string Json, ref string data) {
            WebServiceTLAExterno.FarmAgro.OrdenesExpedicion_03Request inValue = new WebServiceTLAExterno.FarmAgro.OrdenesExpedicion_03Request();
            inValue.Body = new WebServiceTLAExterno.FarmAgro.OrdenesExpedicion_03RequestBody();
            inValue.Body.Json = Json;
            inValue.Body.data = data;
            WebServiceTLAExterno.FarmAgro.OrdenesExpedicion_03Response retVal = ((WebServiceTLAExterno.FarmAgro.WebService_FarmAgroSoap)(this)).OrdenesExpedicion_03(inValue);
            data = retVal.Body.data;
            return retVal.Body.OrdenesExpedicion_03Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceTLAExterno.FarmAgro.OrdenesExpedicion_03Response> WebServiceTLAExterno.FarmAgro.WebService_FarmAgroSoap.OrdenesExpedicion_03Async(WebServiceTLAExterno.FarmAgro.OrdenesExpedicion_03Request request) {
            return base.Channel.OrdenesExpedicion_03Async(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceTLAExterno.FarmAgro.OrdenesExpedicion_03Response> OrdenesExpedicion_03Async(string Json, string data) {
            WebServiceTLAExterno.FarmAgro.OrdenesExpedicion_03Request inValue = new WebServiceTLAExterno.FarmAgro.OrdenesExpedicion_03Request();
            inValue.Body = new WebServiceTLAExterno.FarmAgro.OrdenesExpedicion_03RequestBody();
            inValue.Body.Json = Json;
            inValue.Body.data = data;
            return ((WebServiceTLAExterno.FarmAgro.WebService_FarmAgroSoap)(this)).OrdenesExpedicion_03Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceTLAExterno.FarmAgro.OrdenesASN_01Response WebServiceTLAExterno.FarmAgro.WebService_FarmAgroSoap.OrdenesASN_01(WebServiceTLAExterno.FarmAgro.OrdenesASN_01Request request) {
            return base.Channel.OrdenesASN_01(request);
        }
        
        public bool OrdenesASN_01(string Json, ref string data) {
            WebServiceTLAExterno.FarmAgro.OrdenesASN_01Request inValue = new WebServiceTLAExterno.FarmAgro.OrdenesASN_01Request();
            inValue.Body = new WebServiceTLAExterno.FarmAgro.OrdenesASN_01RequestBody();
            inValue.Body.Json = Json;
            inValue.Body.data = data;
            WebServiceTLAExterno.FarmAgro.OrdenesASN_01Response retVal = ((WebServiceTLAExterno.FarmAgro.WebService_FarmAgroSoap)(this)).OrdenesASN_01(inValue);
            data = retVal.Body.data;
            return retVal.Body.OrdenesASN_01Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceTLAExterno.FarmAgro.OrdenesASN_01Response> WebServiceTLAExterno.FarmAgro.WebService_FarmAgroSoap.OrdenesASN_01Async(WebServiceTLAExterno.FarmAgro.OrdenesASN_01Request request) {
            return base.Channel.OrdenesASN_01Async(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceTLAExterno.FarmAgro.OrdenesASN_01Response> OrdenesASN_01Async(string Json, string data) {
            WebServiceTLAExterno.FarmAgro.OrdenesASN_01Request inValue = new WebServiceTLAExterno.FarmAgro.OrdenesASN_01Request();
            inValue.Body = new WebServiceTLAExterno.FarmAgro.OrdenesASN_01RequestBody();
            inValue.Body.Json = Json;
            inValue.Body.data = data;
            return ((WebServiceTLAExterno.FarmAgro.WebService_FarmAgroSoap)(this)).OrdenesASN_01Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceTLAExterno.FarmAgro.Materiales_11Response WebServiceTLAExterno.FarmAgro.WebService_FarmAgroSoap.Materiales_11(WebServiceTLAExterno.FarmAgro.Materiales_11Request request) {
            return base.Channel.Materiales_11(request);
        }
        
        public bool Materiales_11(string json, ref string data) {
            WebServiceTLAExterno.FarmAgro.Materiales_11Request inValue = new WebServiceTLAExterno.FarmAgro.Materiales_11Request();
            inValue.Body = new WebServiceTLAExterno.FarmAgro.Materiales_11RequestBody();
            inValue.Body.json = json;
            inValue.Body.data = data;
            WebServiceTLAExterno.FarmAgro.Materiales_11Response retVal = ((WebServiceTLAExterno.FarmAgro.WebService_FarmAgroSoap)(this)).Materiales_11(inValue);
            data = retVal.Body.data;
            return retVal.Body.Materiales_11Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceTLAExterno.FarmAgro.Materiales_11Response> WebServiceTLAExterno.FarmAgro.WebService_FarmAgroSoap.Materiales_11Async(WebServiceTLAExterno.FarmAgro.Materiales_11Request request) {
            return base.Channel.Materiales_11Async(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceTLAExterno.FarmAgro.Materiales_11Response> Materiales_11Async(string json, string data) {
            WebServiceTLAExterno.FarmAgro.Materiales_11Request inValue = new WebServiceTLAExterno.FarmAgro.Materiales_11Request();
            inValue.Body = new WebServiceTLAExterno.FarmAgro.Materiales_11RequestBody();
            inValue.Body.json = json;
            inValue.Body.data = data;
            return ((WebServiceTLAExterno.FarmAgro.WebService_FarmAgroSoap)(this)).Materiales_11Async(inValue);
        }
    }
}
