//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceTLAExterno.Accounting {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Accounting.AccountingSoap")]
    public interface AccountingSoap {
        
        // CODEGEN: Generating message contract since element name json from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IntSaldosDiarios", ReplyAction="*")]
        WebServiceTLAExterno.Accounting.IntSaldosDiariosResponse IntSaldosDiarios(WebServiceTLAExterno.Accounting.IntSaldosDiariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IntSaldosDiarios", ReplyAction="*")]
        System.IAsyncResult BeginIntSaldosDiarios(WebServiceTLAExterno.Accounting.IntSaldosDiariosRequest request, System.AsyncCallback callback, object asyncState);
        
        WebServiceTLAExterno.Accounting.IntSaldosDiariosResponse EndIntSaldosDiarios(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name json from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IntCXC", ReplyAction="*")]
        WebServiceTLAExterno.Accounting.IntCXCResponse IntCXC(WebServiceTLAExterno.Accounting.IntCXCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IntCXC", ReplyAction="*")]
        System.IAsyncResult BeginIntCXC(WebServiceTLAExterno.Accounting.IntCXCRequest request, System.AsyncCallback callback, object asyncState);
        
        WebServiceTLAExterno.Accounting.IntCXCResponse EndIntCXC(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name json from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INT_INGRESOS_CXC", ReplyAction="*")]
        WebServiceTLAExterno.Accounting.INT_INGRESOS_CXCResponse INT_INGRESOS_CXC(WebServiceTLAExterno.Accounting.INT_INGRESOS_CXCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INT_INGRESOS_CXC", ReplyAction="*")]
        System.IAsyncResult BeginINT_INGRESOS_CXC(WebServiceTLAExterno.Accounting.INT_INGRESOS_CXCRequest request, System.AsyncCallback callback, object asyncState);
        
        WebServiceTLAExterno.Accounting.INT_INGRESOS_CXCResponse EndINT_INGRESOS_CXC(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IntSaldosDiariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IntSaldosDiarios", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceTLAExterno.Accounting.IntSaldosDiariosRequestBody Body;
        
        public IntSaldosDiariosRequest() {
        }
        
        public IntSaldosDiariosRequest(WebServiceTLAExterno.Accounting.IntSaldosDiariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IntSaldosDiariosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string json;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dataconvert;
        
        public IntSaldosDiariosRequestBody() {
        }
        
        public IntSaldosDiariosRequestBody(string json, string dataconvert) {
            this.json = json;
            this.dataconvert = dataconvert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IntSaldosDiariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IntSaldosDiariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceTLAExterno.Accounting.IntSaldosDiariosResponseBody Body;
        
        public IntSaldosDiariosResponse() {
        }
        
        public IntSaldosDiariosResponse(WebServiceTLAExterno.Accounting.IntSaldosDiariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IntSaldosDiariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IntSaldosDiariosResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dataconvert;
        
        public IntSaldosDiariosResponseBody() {
        }
        
        public IntSaldosDiariosResponseBody(bool IntSaldosDiariosResult, string dataconvert) {
            this.IntSaldosDiariosResult = IntSaldosDiariosResult;
            this.dataconvert = dataconvert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IntCXCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IntCXC", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceTLAExterno.Accounting.IntCXCRequestBody Body;
        
        public IntCXCRequest() {
        }
        
        public IntCXCRequest(WebServiceTLAExterno.Accounting.IntCXCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IntCXCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string json;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dataconvert;
        
        public IntCXCRequestBody() {
        }
        
        public IntCXCRequestBody(string json, string dataconvert) {
            this.json = json;
            this.dataconvert = dataconvert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IntCXCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IntCXCResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceTLAExterno.Accounting.IntCXCResponseBody Body;
        
        public IntCXCResponse() {
        }
        
        public IntCXCResponse(WebServiceTLAExterno.Accounting.IntCXCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IntCXCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IntCXCResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dataconvert;
        
        public IntCXCResponseBody() {
        }
        
        public IntCXCResponseBody(bool IntCXCResult, string dataconvert) {
            this.IntCXCResult = IntCXCResult;
            this.dataconvert = dataconvert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class INT_INGRESOS_CXCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="INT_INGRESOS_CXC", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceTLAExterno.Accounting.INT_INGRESOS_CXCRequestBody Body;
        
        public INT_INGRESOS_CXCRequest() {
        }
        
        public INT_INGRESOS_CXCRequest(WebServiceTLAExterno.Accounting.INT_INGRESOS_CXCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class INT_INGRESOS_CXCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string json;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dataconvert;
        
        public INT_INGRESOS_CXCRequestBody() {
        }
        
        public INT_INGRESOS_CXCRequestBody(string json, string dataconvert) {
            this.json = json;
            this.dataconvert = dataconvert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class INT_INGRESOS_CXCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="INT_INGRESOS_CXCResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceTLAExterno.Accounting.INT_INGRESOS_CXCResponseBody Body;
        
        public INT_INGRESOS_CXCResponse() {
        }
        
        public INT_INGRESOS_CXCResponse(WebServiceTLAExterno.Accounting.INT_INGRESOS_CXCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class INT_INGRESOS_CXCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool INT_INGRESOS_CXCResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dataconvert;
        
        public INT_INGRESOS_CXCResponseBody() {
        }
        
        public INT_INGRESOS_CXCResponseBody(bool INT_INGRESOS_CXCResult, string dataconvert) {
            this.INT_INGRESOS_CXCResult = INT_INGRESOS_CXCResult;
            this.dataconvert = dataconvert;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountingSoapChannel : WebServiceTLAExterno.Accounting.AccountingSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntSaldosDiariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public IntSaldosDiariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string dataconvert {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntCXCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public IntCXCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string dataconvert {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class INT_INGRESOS_CXCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public INT_INGRESOS_CXCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string dataconvert {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountingSoapClient : System.ServiceModel.ClientBase<WebServiceTLAExterno.Accounting.AccountingSoap>, WebServiceTLAExterno.Accounting.AccountingSoap {
        
        private BeginOperationDelegate onBeginIntSaldosDiariosDelegate;
        
        private EndOperationDelegate onEndIntSaldosDiariosDelegate;
        
        private System.Threading.SendOrPostCallback onIntSaldosDiariosCompletedDelegate;
        
        private BeginOperationDelegate onBeginIntCXCDelegate;
        
        private EndOperationDelegate onEndIntCXCDelegate;
        
        private System.Threading.SendOrPostCallback onIntCXCCompletedDelegate;
        
        private BeginOperationDelegate onBeginINT_INGRESOS_CXCDelegate;
        
        private EndOperationDelegate onEndINT_INGRESOS_CXCDelegate;
        
        private System.Threading.SendOrPostCallback onINT_INGRESOS_CXCCompletedDelegate;
        
        public AccountingSoapClient() {
        }
        
        public AccountingSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountingSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountingSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<IntSaldosDiariosCompletedEventArgs> IntSaldosDiariosCompleted;
        
        public event System.EventHandler<IntCXCCompletedEventArgs> IntCXCCompleted;
        
        public event System.EventHandler<INT_INGRESOS_CXCCompletedEventArgs> INT_INGRESOS_CXCCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceTLAExterno.Accounting.IntSaldosDiariosResponse WebServiceTLAExterno.Accounting.AccountingSoap.IntSaldosDiarios(WebServiceTLAExterno.Accounting.IntSaldosDiariosRequest request) {
            return base.Channel.IntSaldosDiarios(request);
        }
        
        public bool IntSaldosDiarios(string json, ref string dataconvert) {
            WebServiceTLAExterno.Accounting.IntSaldosDiariosRequest inValue = new WebServiceTLAExterno.Accounting.IntSaldosDiariosRequest();
            inValue.Body = new WebServiceTLAExterno.Accounting.IntSaldosDiariosRequestBody();
            inValue.Body.json = json;
            inValue.Body.dataconvert = dataconvert;
            WebServiceTLAExterno.Accounting.IntSaldosDiariosResponse retVal = ((WebServiceTLAExterno.Accounting.AccountingSoap)(this)).IntSaldosDiarios(inValue);
            dataconvert = retVal.Body.dataconvert;
            return retVal.Body.IntSaldosDiariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WebServiceTLAExterno.Accounting.AccountingSoap.BeginIntSaldosDiarios(WebServiceTLAExterno.Accounting.IntSaldosDiariosRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginIntSaldosDiarios(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginIntSaldosDiarios(string json, string dataconvert, System.AsyncCallback callback, object asyncState) {
            WebServiceTLAExterno.Accounting.IntSaldosDiariosRequest inValue = new WebServiceTLAExterno.Accounting.IntSaldosDiariosRequest();
            inValue.Body = new WebServiceTLAExterno.Accounting.IntSaldosDiariosRequestBody();
            inValue.Body.json = json;
            inValue.Body.dataconvert = dataconvert;
            return ((WebServiceTLAExterno.Accounting.AccountingSoap)(this)).BeginIntSaldosDiarios(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceTLAExterno.Accounting.IntSaldosDiariosResponse WebServiceTLAExterno.Accounting.AccountingSoap.EndIntSaldosDiarios(System.IAsyncResult result) {
            return base.Channel.EndIntSaldosDiarios(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndIntSaldosDiarios(System.IAsyncResult result, out string dataconvert) {
            WebServiceTLAExterno.Accounting.IntSaldosDiariosResponse retVal = ((WebServiceTLAExterno.Accounting.AccountingSoap)(this)).EndIntSaldosDiarios(result);
            dataconvert = retVal.Body.dataconvert;
            return retVal.Body.IntSaldosDiariosResult;
        }
        
        private System.IAsyncResult OnBeginIntSaldosDiarios(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string json = ((string)(inValues[0]));
            string dataconvert = ((string)(inValues[1]));
            return this.BeginIntSaldosDiarios(json, dataconvert, callback, asyncState);
        }
        
        private object[] OnEndIntSaldosDiarios(System.IAsyncResult result) {
            string dataconvert = this.GetDefaultValueForInitialization<string>();
            bool retVal = this.EndIntSaldosDiarios(result, out dataconvert);
            return new object[] {
                    dataconvert,
                    retVal};
        }
        
        private void OnIntSaldosDiariosCompleted(object state) {
            if ((this.IntSaldosDiariosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.IntSaldosDiariosCompleted(this, new IntSaldosDiariosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void IntSaldosDiariosAsync(string json, string dataconvert) {
            this.IntSaldosDiariosAsync(json, dataconvert, null);
        }
        
        public void IntSaldosDiariosAsync(string json, string dataconvert, object userState) {
            if ((this.onBeginIntSaldosDiariosDelegate == null)) {
                this.onBeginIntSaldosDiariosDelegate = new BeginOperationDelegate(this.OnBeginIntSaldosDiarios);
            }
            if ((this.onEndIntSaldosDiariosDelegate == null)) {
                this.onEndIntSaldosDiariosDelegate = new EndOperationDelegate(this.OnEndIntSaldosDiarios);
            }
            if ((this.onIntSaldosDiariosCompletedDelegate == null)) {
                this.onIntSaldosDiariosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnIntSaldosDiariosCompleted);
            }
            base.InvokeAsync(this.onBeginIntSaldosDiariosDelegate, new object[] {
                        json,
                        dataconvert}, this.onEndIntSaldosDiariosDelegate, this.onIntSaldosDiariosCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceTLAExterno.Accounting.IntCXCResponse WebServiceTLAExterno.Accounting.AccountingSoap.IntCXC(WebServiceTLAExterno.Accounting.IntCXCRequest request) {
            return base.Channel.IntCXC(request);
        }
        
        public bool IntCXC(string json, ref string dataconvert) {
            WebServiceTLAExterno.Accounting.IntCXCRequest inValue = new WebServiceTLAExterno.Accounting.IntCXCRequest();
            inValue.Body = new WebServiceTLAExterno.Accounting.IntCXCRequestBody();
            inValue.Body.json = json;
            inValue.Body.dataconvert = dataconvert;
            WebServiceTLAExterno.Accounting.IntCXCResponse retVal = ((WebServiceTLAExterno.Accounting.AccountingSoap)(this)).IntCXC(inValue);
            dataconvert = retVal.Body.dataconvert;
            return retVal.Body.IntCXCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WebServiceTLAExterno.Accounting.AccountingSoap.BeginIntCXC(WebServiceTLAExterno.Accounting.IntCXCRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginIntCXC(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginIntCXC(string json, string dataconvert, System.AsyncCallback callback, object asyncState) {
            WebServiceTLAExterno.Accounting.IntCXCRequest inValue = new WebServiceTLAExterno.Accounting.IntCXCRequest();
            inValue.Body = new WebServiceTLAExterno.Accounting.IntCXCRequestBody();
            inValue.Body.json = json;
            inValue.Body.dataconvert = dataconvert;
            return ((WebServiceTLAExterno.Accounting.AccountingSoap)(this)).BeginIntCXC(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceTLAExterno.Accounting.IntCXCResponse WebServiceTLAExterno.Accounting.AccountingSoap.EndIntCXC(System.IAsyncResult result) {
            return base.Channel.EndIntCXC(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndIntCXC(System.IAsyncResult result, out string dataconvert) {
            WebServiceTLAExterno.Accounting.IntCXCResponse retVal = ((WebServiceTLAExterno.Accounting.AccountingSoap)(this)).EndIntCXC(result);
            dataconvert = retVal.Body.dataconvert;
            return retVal.Body.IntCXCResult;
        }
        
        private System.IAsyncResult OnBeginIntCXC(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string json = ((string)(inValues[0]));
            string dataconvert = ((string)(inValues[1]));
            return this.BeginIntCXC(json, dataconvert, callback, asyncState);
        }
        
        private object[] OnEndIntCXC(System.IAsyncResult result) {
            string dataconvert = this.GetDefaultValueForInitialization<string>();
            bool retVal = this.EndIntCXC(result, out dataconvert);
            return new object[] {
                    dataconvert,
                    retVal};
        }
        
        private void OnIntCXCCompleted(object state) {
            if ((this.IntCXCCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.IntCXCCompleted(this, new IntCXCCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void IntCXCAsync(string json, string dataconvert) {
            this.IntCXCAsync(json, dataconvert, null);
        }
        
        public void IntCXCAsync(string json, string dataconvert, object userState) {
            if ((this.onBeginIntCXCDelegate == null)) {
                this.onBeginIntCXCDelegate = new BeginOperationDelegate(this.OnBeginIntCXC);
            }
            if ((this.onEndIntCXCDelegate == null)) {
                this.onEndIntCXCDelegate = new EndOperationDelegate(this.OnEndIntCXC);
            }
            if ((this.onIntCXCCompletedDelegate == null)) {
                this.onIntCXCCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnIntCXCCompleted);
            }
            base.InvokeAsync(this.onBeginIntCXCDelegate, new object[] {
                        json,
                        dataconvert}, this.onEndIntCXCDelegate, this.onIntCXCCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceTLAExterno.Accounting.INT_INGRESOS_CXCResponse WebServiceTLAExterno.Accounting.AccountingSoap.INT_INGRESOS_CXC(WebServiceTLAExterno.Accounting.INT_INGRESOS_CXCRequest request) {
            return base.Channel.INT_INGRESOS_CXC(request);
        }
        
        public bool INT_INGRESOS_CXC(string json, ref string dataconvert) {
            WebServiceTLAExterno.Accounting.INT_INGRESOS_CXCRequest inValue = new WebServiceTLAExterno.Accounting.INT_INGRESOS_CXCRequest();
            inValue.Body = new WebServiceTLAExterno.Accounting.INT_INGRESOS_CXCRequestBody();
            inValue.Body.json = json;
            inValue.Body.dataconvert = dataconvert;
            WebServiceTLAExterno.Accounting.INT_INGRESOS_CXCResponse retVal = ((WebServiceTLAExterno.Accounting.AccountingSoap)(this)).INT_INGRESOS_CXC(inValue);
            dataconvert = retVal.Body.dataconvert;
            return retVal.Body.INT_INGRESOS_CXCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WebServiceTLAExterno.Accounting.AccountingSoap.BeginINT_INGRESOS_CXC(WebServiceTLAExterno.Accounting.INT_INGRESOS_CXCRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginINT_INGRESOS_CXC(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginINT_INGRESOS_CXC(string json, string dataconvert, System.AsyncCallback callback, object asyncState) {
            WebServiceTLAExterno.Accounting.INT_INGRESOS_CXCRequest inValue = new WebServiceTLAExterno.Accounting.INT_INGRESOS_CXCRequest();
            inValue.Body = new WebServiceTLAExterno.Accounting.INT_INGRESOS_CXCRequestBody();
            inValue.Body.json = json;
            inValue.Body.dataconvert = dataconvert;
            return ((WebServiceTLAExterno.Accounting.AccountingSoap)(this)).BeginINT_INGRESOS_CXC(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceTLAExterno.Accounting.INT_INGRESOS_CXCResponse WebServiceTLAExterno.Accounting.AccountingSoap.EndINT_INGRESOS_CXC(System.IAsyncResult result) {
            return base.Channel.EndINT_INGRESOS_CXC(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndINT_INGRESOS_CXC(System.IAsyncResult result, out string dataconvert) {
            WebServiceTLAExterno.Accounting.INT_INGRESOS_CXCResponse retVal = ((WebServiceTLAExterno.Accounting.AccountingSoap)(this)).EndINT_INGRESOS_CXC(result);
            dataconvert = retVal.Body.dataconvert;
            return retVal.Body.INT_INGRESOS_CXCResult;
        }
        
        private System.IAsyncResult OnBeginINT_INGRESOS_CXC(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string json = ((string)(inValues[0]));
            string dataconvert = ((string)(inValues[1]));
            return this.BeginINT_INGRESOS_CXC(json, dataconvert, callback, asyncState);
        }
        
        private object[] OnEndINT_INGRESOS_CXC(System.IAsyncResult result) {
            string dataconvert = this.GetDefaultValueForInitialization<string>();
            bool retVal = this.EndINT_INGRESOS_CXC(result, out dataconvert);
            return new object[] {
                    dataconvert,
                    retVal};
        }
        
        private void OnINT_INGRESOS_CXCCompleted(object state) {
            if ((this.INT_INGRESOS_CXCCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.INT_INGRESOS_CXCCompleted(this, new INT_INGRESOS_CXCCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void INT_INGRESOS_CXCAsync(string json, string dataconvert) {
            this.INT_INGRESOS_CXCAsync(json, dataconvert, null);
        }
        
        public void INT_INGRESOS_CXCAsync(string json, string dataconvert, object userState) {
            if ((this.onBeginINT_INGRESOS_CXCDelegate == null)) {
                this.onBeginINT_INGRESOS_CXCDelegate = new BeginOperationDelegate(this.OnBeginINT_INGRESOS_CXC);
            }
            if ((this.onEndINT_INGRESOS_CXCDelegate == null)) {
                this.onEndINT_INGRESOS_CXCDelegate = new EndOperationDelegate(this.OnEndINT_INGRESOS_CXC);
            }
            if ((this.onINT_INGRESOS_CXCCompletedDelegate == null)) {
                this.onINT_INGRESOS_CXCCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnINT_INGRESOS_CXCCompleted);
            }
            base.InvokeAsync(this.onBeginINT_INGRESOS_CXCDelegate, new object[] {
                        json,
                        dataconvert}, this.onEndINT_INGRESOS_CXCDelegate, this.onINT_INGRESOS_CXCCompletedDelegate, userState);
        }
    }
}
